Feature/fix-order-history-api
teamdev-ecommerce-202409/E-Commerce-Webapp-with-Stripe-Sync pull request #23
Opened 2024-10-21 13:57 UTC by sunny-side-app

フロントからバックエンドAPI経由で注文履歴一覧を取得するため、関連するモデル、シリアライザを一部修正しました。

2024-10-21 14:59 UTC, haru864 requested changes

2024-10-21 14:59 UTC, haru864 commented on src/clothes_shop/serializers.py
> +# OrderItemSerializerを追加
コーナーケースのバグみたいな、ソースだけではわからない注意事項以外のコメントは削除でお願いします
（ほかの箇所も）

2024-10-21 14:59 UTC, haru864 commented on src/clothes_shop/models.py
> +    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='order_items') #Orderオブジェクトから関連するOrderItemを取得するため
https://note.com/shushuitie/n/n55c61161212d
related_nameは逆参照で使うみたいですが、OrderItemからOrderを逆参照するケースってあるのでしょうか。
注文履歴なら、
１．注文一覧を取得
２．注文IDから注文した商品を取得
でよくて、商品から注文への移動はないかと。

2024-10-22 12:57 UTC, sunny-side-app commented
@haru864 

> コーナーケースのバグみたいな、ソースだけではわからない注意事項以外のコメントは削除でお願いします
（ほかの箇所も）

対応させていただきましたのでご確認をお願いします。
不要ならば消しますが、Viewやシリアライザを中心に一部修正し似たようなクラスが存在するため、その部分の用途だけはコメントで残しました。

また通知メールに記載のあった下記コメントに回答させていただきます。下記方法でも良いかと思いますが、OrderItemを取得するため注文明細の数だけクライアントからAPI実行、データベースクエリすることなると思うので、Modelのrelated_name()やViewのprefetch_related()を使って事前に注文一覧・明細をまとめて取得できるようにしております。

> related_nameは逆参照で使うみたいですが、OrderItemからOrderを逆参照するケースってあるのでしょうか。
> 注文履歴なら、
> １．注文一覧を取得
> ２．注文IDから注文した商品を取得
> でよくて、商品から注文への移動はないかと。

2024-10-22 17:12 UTC, haru864 requested changes

2024-10-22 17:12 UTC, haru864 commented on docker-entrypoint.sh
>  if /django/venv/bin/python3 manage.py migrate; then
マイグレーションファイルはgitで管理するので、コンテナ起動時にmakemigrationsは不要です。

2024-10-22 17:12 UTC, haru864 commented on src/clothes_shop/serializers.py
> +class OrderSerializer(serializers.ModelSerializer):# Order一覧のみ取得したい場合用
コメント削除して、クラス名を変更（OrderSerializer→OrderSummarySerializer）のほうがわかりやすいと思います。

2024-10-22 17:12 UTC, haru864 commented on src/clothes_shop/serializers.py
> +        fields = ("id", "first_name", "last_name", "email", "role", "address")
user_nameを"first_name", "last_name"に分けたのって何のためなのでしょうか。

2024-10-22 17:12 UTC, haru864 commented on src/clothes_shop/serializers.py
> +class OrderDetailSerializer(serializers.ModelSerializer):# 注文詳細も取得したい場合用
コメント削除して、クラス名を変更（OrderSerializer→OrderWithItemsSerializer）のほうがわかりやすいと思います。

2024-10-27 05:04 UTC, sunny-side-app commented
ご指摘いただいていた箇所の修正と、注文履歴取得時にProductテーブル情報も取得できるようシリアライザを修正を行いました。

2024-11-02 21:56 UTC, Karukan0814 requested changes
ログイン機能完成後、諸々変更のこと

2024-11-02 21:56 UTC, Karukan0814 commented on src/clothes_shop/tests/order/test_models.py
> +    def setUp(self):
ログイン機能のマージ後、コンフリクト解消してください、

2024-11-02 21:56 UTC, Karukan0814 commented on src/clothes_shop/views.py
> +        user_id = self.request.query_params.get('user_id')
ログイン機能完成後、ログインユーザーからユーザー情報取得に変更してください

2024-11-11 03:19 UTC, closed without merging