製品一括削除のためにエンドポイントを追加
teamdev-ecommerce-202409/E-Commerce-Webapp-with-Stripe-Sync pull request #28
Opened 2024-10-27 10:54 UTC by haru864

2024-10-28 00:36 UTC, Karukan0814 requested changes
リクエストinループの変更要望

2024-10-28 00:36 UTC, Karukan0814 commented on src/clothes_shop/views/product_views.py
>          for product_id in product_ids:
for文の中でリクエスト呼び出しを回すとパフォーマンスが落ちるので、Product.objects.filter(id__in=product_ids).update(is_deleted=True)で、指定idを一括で更新した方がよいと思います。

2024-10-28 11:56 UTC, haru864 commented on src/clothes_shop/views/product_views.py
>          for product_id in product_ids:
@Karukan0814 
修正しました。
ee92bcc72e6ff112cf1e0b0e13deb66d47fc6320

2024-10-30 14:23 UTC, Karukan0814 approved these changes

2024-10-30 14:23 UTC, merged