Feature/get profile user data
teamdev-ecommerce-202409/E-Commerce-Webapp-with-Stripe-Sync pull request #40
Opened 2024-11-08 16:07 UTC by sunny-side-app

プロフィール編集、削除で利用するバックエンドAPIを作成しました。

### 確認コマンド例(curlの例)

1. トークン取得 ※is_activeがTrueのUserの必要あり
`curl -X POST http://localhost:8081/api/token/ -d "email=testuser@example.com" -d "password=testpass"`
2. プロフィール取得 ※1で取得したアクセストークンをセット
`curl -X GET http://localhost:8081/api/profile/ -H "Authorization: Bearer <access_token>"`
3. プロフィール編集
`curl -X PATCH http://localhost:8081/api/profile/ -H "Authorization: Bearer <access_token>" -d "name=Updated User" -d "address=123 Updated Street"`
4. プロフィール削除
`curl -X DELETE http://localhost:8081/api/profile/ -H "Authorization: Bearer <access_token>"`

2024-11-09 17:26 UTC, Karukan0814 requested changes

2024-11-09 17:26 UTC, Karukan0814 commented on src/clothes_shop/views/user_views.py
> +class UserProfileView(generics.RetrieveUpdateDestroyAPIView):
ログインユーザーが自分のユーザーデータも物理削除できる仕様になっているのはちょっと怖いです。deleteはadminに限るとかできませんか？

2024-11-09 17:31 UTC, Karukan0814 requested changes

2024-11-09 17:31 UTC, Karukan0814 commented on src/clothes_shop/views/user_views.py
> +class UserProfileView(generics.RetrieveUpdateDestroyAPIView):
あと、ユーザーデータを物理削除すると、紐づくFavoriteやOrdersはどうなるでしょう？一緒に物理削除しますか？少なくともOrdersはしてはいけませんよね。　ユーザーデータの物理削除は基本的に行わない方がいいです。論理削除がせいぜいなので、今回のデータモデルの場合はis_active=falseが現実的でしょうね。
なので、私はdeleteの口をそもそも閉じるor 周辺テーブルの影響も考慮した上でadminユーザーに限る　がよいかと

2024-11-10 12:39 UTC, sunny-side-app commented on src/clothes_shop/views/user_views.py
> +class UserProfileView(generics.RetrieveUpdateDestroyAPIView):
おっしゃる通り、ユーザーの削除自体、機能要件にもありませんし現状口は不要かと思いましたので汎用APIViewをRetrieveUpdateAPIViewに修正しました。

2024-11-10 12:41 UTC, sunny-side-app commented
いただいた指摘対応しました。
また、スプリントレビュー#4で指摘いただいたように、認証観点でUserのViewにユニットテストが無かったので、追加しました。

2024-11-11 00:42 UTC, Karukan0814 approved these changes
マージしてフロントのプロフィール表示と編集作成してください

2024-11-12 03:10 UTC, merged