Feature/add user registration func
teamdev-ecommerce-202409/E-Commerce-Webapp-with-Stripe-Sync pull request #56
Opened 2024-11-15 14:38 UTC by sunny-side-app

バックエンド側のユーザー登録機能(サインアップ時のバックエンドの処理)を実装しました。
メール確認機能は今後追加予定です。

2024-11-15 16:34 UTC, haru864 requested changes

2024-11-15 16:34 UTC, haru864 commented on .vscode/settings.json
この設定変更は必要でしょうか？
これまでの設定とは異なる挙動になると思います。

2024-11-15 16:34 UTC, haru864 commented on src/clothes_shop/serializers/user_serializers.py
> +        read_only_fields = ['id', 'is_active', 'is_staff']
ダブルクォートからシングルクォートに変わっていますが、変更前のsettings.jsonだと保存時にダブルクォートに変換されるはず。
settings.jsonを変更してマージすると既存のファイルでも不要な変更が発生すると思われるため、settings.jsonは変えたくないです。

2024-11-15 16:34 UTC, haru864 commented on src/clothes_shop/serializers/user_serializers.py
> +        )
サインアップのリクエストパラメータは、
name, email, address, password
にすべきだと思います。
roleはregisteredをバックエンドでセットする。
このままだとだれでもadmin作れちゃうのでは。

2024-11-15 16:34 UTC, haru864 commented on src/clothes_shop/urls.py
> +    path('api/profile/', user_views.UserProfileView.as_view(), name='user-profile'),
ここだけシングルクォートなのは、やはりsettings.jsonが効いてないのでは。

2024-11-16 13:34 UTC, sunny-side-app commented on .vscode/settings.json
> users_viewsとかテストコードみたかんじ、お二人のうち少なくとも一人は.vscode/settings.jsonのフォーマッターが効いてないっぽいので確認してほしいです。

以前別途こちらのコメントをいただいてましたが、前バージョンのもので問題ないでしょうか。元に戻しました。

2024-11-16 13:35 UTC, sunny-side-app commented on src/clothes_shop/serializers/user_serializers.py
> +        read_only_fields = ['id', 'is_active', 'is_staff']
ダブルクォートに戻しました

2024-11-16 13:35 UTC, sunny-side-app commented on src/clothes_shop/serializers/user_serializers.py
> +        )
対応させていただきました

2024-11-16 16:50 UTC, haru864 commented on .vscode/settings.json
変更しなくても効いているはずなのですが、保存してもフォーマットされていないから変更したということでしょうか

2024-11-16 16:50 UTC, haru864 commented on .vscode/settings.json
@sunny-side-app 
変更しなくても効いているはずなのですが、保存してもフォーマットされていないから変更したということでしょうか

2024-11-16 23:48 UTC, Karukan0814 requested changes

2024-11-16 23:48 UTC, Karukan0814 commented on src/clothes_shop/views/user_views.py
> +            api_exception.status_code = 500
logger.errorでエラーログに書き出して

2024-11-16 23:48 UTC, Karukan0814 commented on src/clothes_shop/views/user_views.py
> +            "message": "ユーザー登録が成功しました。メールを確認してください。",
メッセ―じ変えた方がいい。メールみて、リンク踏んで認証して～、みたいな文言いれて

2024-11-16 23:48 UTC, Karukan0814 commented on src/clothes_shop/views/user_views.py
> +            customer_data = CustomerData(
もう一度、email認証を試みてメールのtokenがexpireしたユーザーだったらどうする？まず、すでに登録されているemailか確認→登録されていてis_active=Trueであれば不正エラー。is_active=Falseであればemail認証失敗ユーザーなので、既存のデータ再利用。　の流れになるはず

2024-11-17 13:34 UTC, sunny-side-app commented on .vscode/settings.json
そういう意図でした。調べてみましたが、フォーマットは有効にできていないようです。

2024-11-17 13:35 UTC, sunny-side-app commented on src/clothes_shop/views/user_views.py
> +            api_exception.status_code = 500
対応させていただきました

2024-11-17 13:35 UTC, sunny-side-app commented on src/clothes_shop/views/user_views.py
> +            "message": "ユーザー登録が成功しました。メールを確認してください。",
対応させていただきました

2024-11-17 13:35 UTC, sunny-side-app commented on src/clothes_shop/views/user_views.py
> +            customer_data = CustomerData(
対応させていただきました。場合分けのイメージが合っているかcreate()メソッドを確認いただけるとありがたいです。

2024-11-18 09:13 UTC, Karukan0814 requested changes

2024-11-18 09:13 UTC, Karukan0814 commented on src/clothes_shop/views/user_views.py
> +                    {"error": "メール認証が未完了です。メールを再送信したのでメールを確認し、リンクをクリックしてメール認証を完了させてください。"},
ここはメール再送信なので、エラーではなく、メール再送信なので、200OK
なのでは？　あと、どこでメールとばしているか教えて。

2024-11-18 15:56 UTC, sunny-side-app commented on src/clothes_shop/views/user_views.py
> +                    {"error": "メール認証が未完了です。メールを再送信したのでメールを確認し、リンクをクリックしてメール認証を完了させてください。"},
> ここはメール再送信なので、エラーではなく、メール再送信なので、200OKなのでは？

ご認識の通りなので、ステータス変更しました。

> メール確認機能＝メールリンククリック後の動作　と思っていたけど、メール送信そのもの　を後にするってこと？　それならこれら指摘点直したらマージしていいよ。そしてすぐにメールにとりかかろう

わかりづらくて申し訳ありません。
PRが肥大化しそうだったので、ユーザーのサインアップのフォーム送信時の更新をまず見ていただきたい意図でした。

下記を追加しました。

- メール確認機能(メールリンククリック後の動作)：EmailConfirmationView
- メール送信機能(サインアップ時のメール送信、メール再送信)：UserSignupViewの追加部分、email_service.py
- メール送信機能(メール再送信)： ResendConfirmationEmailView ※一応作成しましたが、UserSignupViewの中で再送信までしており現状不要なので、現状構成で問題なければ削除します

2024-11-21 01:17 UTC, Karukan0814 approved these changes

2024-11-21 01:17 UTC, Karukan0814 commented on src/djangopj/settings.py
> +EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False") == "True"
これってホストするメールアドレスが必要ってことだよね？メールがとぶかの実際の確認はすんでいるんだよね？具体的にどのアドレスでどのような設定をすると動くようになるかどこかに書き記して、開発者だれでもメールとばせるように設定書いておこう。contribute,mdとかに。　それでマージしちゃって。　すぐにフロントにとりかかろう

2024-11-21 10:23 UTC, sunny-side-app commented on src/djangopj/settings.py
> +EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False") == "True"
> これってホストするメールアドレスが必要ってことだよね？メールがとぶかの実際の確認はすんでいるんだよね？
はい、ご認識の通りで確認済みです。

CONTRIBUTING.md更新できておらず失礼いたしました。更新しました。

2024-11-21 10:24 UTC, merged